

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TestFinal.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Vizija : DbContext
{
    public Vizija()
        : base("name=Vizija")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<GlavnaTabela> GlavnaTabelas { get; set; }

    public virtual DbSet<Kontakt> Kontakts { get; set; }

    public virtual DbSet<KontaktMail> KontaktMails { get; set; }

    public virtual DbSet<KontaktTelefon> KontaktTelefons { get; set; }

}

}

